# @author Zoe
# @version 1.0
# Archivo de configuración para el acceso a la base de datos del sistema.

# Driver JDBC específico para la gestión y reconocimiento del motor SQLite.
DRIVER=org.sqlite.JDBC

# Ruta de conexión orientada al archivo físico de la base de datos local.
URL=jdbc:sqlite:DB/tiendaFnac.db